# Generated by Django 5.1 on 2024-08-28 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sucursales',
            old_name='direccion_sucursal',
            new_name='direccion_sucursales',
        ),
        migrations.RenameField(
            model_name='sucursales',
            old_name='nombre_sucursal',
            new_name='nombre_sucursales',
        ),
    ]
