# Generated by Django 5.1 on 2024-09-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_comprador_venta_comprador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprador',
            options={'verbose_name': 'Comprador', 'verbose_name_plural': 'Compradores'},
        ),
        migrations.AddField(
            model_name='comprador',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
