# Generated by Django 5.1 on 2024-08-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_frutas', models.CharField(max_length=50, unique=True)),
                ('kilo_frutas', models.IntegerField()),
                ('monto_frutas', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
