# Generated by Django 5.1 on 2024-09-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='detalle_producto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
