# Generated by Django 5.1 on 2024-09-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto_detalle_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='beneficio_producto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
