# Generated by Django 5.1 on 2024-09-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto_beneficio_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('FRUTA', 'Fruta'), ('VERDURA', 'Verdura'), ('OFERTA', 'Oferta')], max_length=20),
        ),
    ]
